---
- name: Install Apache HTTPD
  hosts: all
  tasks:
    - name: install httpd
      ansible.builtin.dnf:
        name: 
          - httpd
          - mod_ssl
        state: latest
    - name: deploy index.html
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/html/index.html
    - name: start httpd
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
    - name: open firewall port 80
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
    - name: open firewall port 443
      ansible.posix.firewalld:
        service: https
        permanent: true
        state: enabled
        immediate: true
